title: Change material when collided with 
hero_image: images/banner.png
description: Change material when collided with
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Change material when collided with 
